import { useRef, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router'
import { useAuth } from '../auth/AuthContext'
import { SubmitButton, TextField } from '../components/primitives'
import { formatVnd, formatVietnamTime } from '../lib/contracts'
import { orderStatuses } from '../services/orders'
import { orderManagement } from '../services/orderManagement'
import { ApiError } from '../services/errors'
import { ResourceNotice, TextAreaField, ActionNotice } from './AdminCatalogShared'
import { useMutation, useResource } from './adminCatalogHooks'
import { OrderPayments } from './OrderPayments'
export function OrderListPage({ admin = false }: { admin?: boolean }) {
  const auth = useAuth(), [params, setParams] = useSearchParams()
  const resource = useResource(auth.user?.userId + ':' + admin + ':' + params, signal => orderManagement.list(params, admin, signal)), page = resource.data
  function turn(value: number) { const next = new URLSearchParams(params); next.set('page', String(value)); setParams(next) }
  return <section className="page-section"><span className="eyebrow">{admin ? 'QUẢN LÝ ĐƠN' : 'TÀI KHOẢN'}</span><h1>{admin ? 'Đơn hàng' : 'Đơn hàng của tôi'}</h1>
    <form key={params.toString()} className="catalog-filters order-filters" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget), next = new URLSearchParams(); for (const key of ['status', 'fromDate', 'toDate', 'pageSize', ...(admin ? ['email', 'customerId'] : [])]) { const value = String(data.get(key) ?? '').trim(); if (value) next.set(key, value) } setParams(next) }}>
      <label className="field">Trạng thái đơn<select name="status" defaultValue={params.get('status') ?? ''}><option value="">Tất cả trạng thái</option>{Object.entries(orderStatuses).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
      <TextField label="Từ ngày" name="fromDate" type="date" defaultValue={params.get('fromDate') ?? ''} /><TextField label="Đến hết ngày" name="toDate" type="date" defaultValue={params.get('toDate') ?? ''} />
      {admin && <><TextField label="Email khách hàng" name="email" type="email" maxLength={256} defaultValue={params.get('email') ?? ''} /><TextField label="ID tài khoản khách" name="customerId" defaultValue={params.get('customerId') ?? ''} hint="Để trống để gồm cả khách vãng lai." /></>}
      <label className="field">Số đơn mỗi trang<select name="pageSize" defaultValue={params.get('pageSize') ?? '20'}>{[1, 10, 20, 50, 100].map(n => <option key={n}>{n}</option>)}</select></label><SubmitButton>Lọc đơn hàng</SubmitButton><SubmitButton type="button" className="button-outline" onClick={() => setParams({})}>Xóa bộ lọc</SubmitButton>
    </form><p className="muted">Ngày được tính theo giờ Việt Nam, bao gồm toàn bộ ngày kết thúc.</p>
    {!page ? <ResourceNotice error={resource.error} reload={resource.reload} loadingText="Đang tải đơn hàng…" /> : <>{!page.items.length ? <p className="notice">Không có đơn hàng phù hợp.</p> : <ul className="catalog-list">{page.items.map(o => <li key={o.id} className="catalog-row order-row"><div><h2>{o.orderNumber}</h2><p>{orderStatuses[o.status]} · {o.paymentMethod === 'COD' ? 'Thanh toán khi nhận hàng' : 'Chuyển khoản'}</p><p>{o.recipientName} · {formatVietnamTime(o.createdAt)}</p>{admin && <p>{o.customerEmail} · {o.customerId ? 'Tài khoản khách hàng' : 'Khách vãng lai'}</p>}<strong>{formatVnd(o.grandTotal)}</strong></div><Link className="button button-outline" to={(admin ? '/admin/orders/' : '/account/orders/') + o.id}>Xem đơn {o.orderNumber}</Link></li>)}</ul>}
      <nav className="catalog-pagination" aria-label="Phân trang đơn hàng"><SubmitButton type="button" disabled={page.page <= 1} onClick={() => turn(page.page - 1)}>Trang trước</SubmitButton><span>Trang {page.page} / {Math.max(1, Math.ceil(page.totalCount / page.pageSize))} · {page.totalCount} đơn</span><SubmitButton type="button" disabled={page.page * page.pageSize >= page.totalCount} onClick={() => turn(page.page + 1)}>Trang sau</SubmitButton></nav></>}
  </section>
}
export function OrderDetailPage({ admin = false }: { admin?: boolean }) {
  const { id = '' } = useParams(), auth = useAuth()
  const resource = useResource(auth.user?.userId + ':' + admin + ':' + id, signal => orderManagement.detail(id, admin, signal)), detail = resource.data, o = detail?.snapshot
  return <section className="page-section order-detail-page"><span className="eyebrow">CHI TIẾT ĐƠN</span><h1>{o ? 'Đơn ' + o.orderNumber : 'Chi tiết đơn hàng'}</h1><Link className="button button-outline" to={admin ? '/admin/orders' : '/account/orders'}>Về danh sách đơn</Link>
    {!detail || !o ? <ResourceNotice error={resource.error} reload={resource.reload} loadingText="Đang tải chi tiết đơn…" /> : <><div className="order-detail-grid"><section className="catalog-panel"><h2>Đơn hàng đã đặt</h2><p>{orderStatuses[o.status]} · {o.paymentMethod === 'COD' ? 'Thanh toán khi nhận hàng' : 'Chuyển khoản'}</p><p>Đặt lúc {formatVietnamTime(o.createdAt)}</p>{o.paymentDueAt && <p>Hạn thanh toán: {formatVietnamTime(o.paymentDueAt)}</p>}<ul className="order-lines">{o.items.map(i => <li key={i.id}><strong>{i.productName}</strong><span>{i.variant} · SKU: {i.sku}</span><span>{i.quantity} × {formatVnd(i.unitPrice - i.unitDiscount)}</span><strong>{formatVnd(i.lineTotal)}</strong></li>)}</ul><dl><div><dt>Tiền hàng</dt><dd>{formatVnd(o.subtotal)}</dd></div><div><dt>Giảm giá</dt><dd>{formatVnd(o.discountTotal)}</dd></div><div><dt>Phí giao hàng</dt><dd>{formatVnd(o.shippingFee)}</dd></div><div><dt>Tổng cộng</dt><dd>{formatVnd(o.grandTotal)}</dd></div></dl></section>
    <section className="catalog-panel"><h2>Thông tin nhận hàng</h2><p>{o.recipientName} · {o.phone}</p><p>{[o.addressLine, o.locality, o.province, 'Việt Nam'].filter(Boolean).join(', ')}</p>{o.note && <p>Ghi chú khách: {o.note}</p>}{admin && <p>Email đặt đơn: {detail.customerEmail}</p>}<h2>Lịch sử đơn</h2><ol className="order-timeline">{o.timeline.map((h, i) => <li key={i}>{orderStatuses[h.toStatus as keyof typeof orderStatuses]} · {formatVietnamTime(h.createdAt)}</li>)}</ol></section></div>
    <OrderPayments key={id + ':' + admin} id={id} area={admin ? 'admin' : 'me'} changed={resource.reload} />
    {admin && <><section className="catalog-panel"><h2>Lịch sử quản trị</h2><ol className="order-timeline">{detail.history?.map(h => <li key={h.id}>{orderStatuses[h.toStatus]} · {formatVietnamTime(h.createdAt)}<p>{h.actorType === 'Admin' ? 'Quản trị viên' : h.actorType === 'Customer' ? 'Khách hàng' : 'Hệ thống'}{h.actorUserId ? ' · ' + h.actorUserId : ''}</p>{h.reason && <p>{h.reason}</p>}</li>)}</ol><h2>Hàng giữ cho đơn</h2>{detail.reservations?.map(r => <p key={r.orderItemId}>Phiên bản {r.variantId} · {r.quantity} sản phẩm · {r.status === 'Active' ? 'Đang giữ' : r.status === 'Consumed' ? 'Đã xuất' : 'Đã giải phóng'}{r.expiresAt ? ' · Hạn giữ ' + formatVietnamTime(r.expiresAt) : ''}</p>)}{detail.refunds?.map(r => <p key={r.id}>Hoàn tiền hàng {formatVnd(r.merchandiseAmount)}, phí giao hàng {formatVnd(r.shippingAmount)} · {r.status === 'Completed' ? 'Đã hoàn' : r.status === 'Pending' ? 'Chờ hoàn' : 'Hoàn thất bại'}</p>)}</section>
      <InternalNotes key={id} id={id} notes={detail.notes ?? []} reload={resource.reload} /></>}
    </>}
  </section>
}
function InternalNotes({ id, notes, reload }: { id: string; notes: NonNullable<import('../services/orderManagement').OrderDetail['notes']>; reload: () => void }) {
  const [text, setText] = useState(''), [attempt, setAttempt] = useState<{ text: string; key: string }>(), action = useMutation(), lock = useRef(false)
  const frozen = !!attempt
  function submit() {
    if (lock.current || action.busy || !text.trim()) return
    lock.current = true; const current = attempt ?? { text: text.trim(), key: crypto.randomUUID() }; setAttempt(current)
    void action.run(async signal => { try { return await orderManagement.note(id, current.text, current.key, signal) } catch (e) { if (e instanceof ApiError && e.status > 0 && e.status < 500 && e.code !== 'CHECKOUT_BUSY') setAttempt(undefined); throw e } }, () => { setText(''); setAttempt(undefined); reload() }, 'Đã lưu ghi chú nội bộ.').finally(() => { lock.current = false })
  }
  return <section className="catalog-panel"><h2>Ghi chú nội bộ</h2><p className="muted">Chỉ quản trị viên xem được. Hiển thị tối đa 50 ghi chú mới nhất.</p><form onSubmit={e => { e.preventDefault(); submit() }}><fieldset disabled={frozen || action.busy} className="checkout-fields"><TextAreaField label="Nội dung ghi chú nội bộ" value={text} onChange={setText} maxLength={500} /></fieldset><SubmitButton busy={action.busy} disabled={!text.trim()}>{attempt ? 'Thử lưu lại ghi chú' : 'Lưu ghi chú'}</SubmitButton></form><ActionNotice action={action} />{notes.map(n => <article key={n.id} className="order-note"><p>{n.text}</p><small>{formatVietnamTime(n.createdAt)} · {n.actorUserId}</small></article>)}</section>
}
export function NotificationsPage({ admin = false }: { admin?: boolean }) {
  const auth = useAuth(), [params, setParams] = useSearchParams(), resource = useResource(auth.user?.userId + ':' + admin + ':' + params, signal => orderManagement.notices(params, signal, admin)), action = useMutation(), page = resource.data
  return <section className="page-section"><span className="eyebrow">{admin ? 'QUẢN TRỊ CỬA HÀNG' : 'TÀI KHOẢN'}</span><h1>{admin ? 'Thông báo quản trị' : 'Thông báo'}</h1>{page && <p role="status">{page.unreadCount} thông báo chưa đọc</p>}<label className="checkout-consent"><input key={params.get('unreadOnly') ?? ''} type="checkbox" defaultChecked={params.get('unreadOnly') === 'true'} onChange={e => setParams(e.target.checked ? { unreadOnly: 'true' } : {})} /> Chỉ xem chưa đọc</label><ActionNotice action={action} />
    {!page ? <ResourceNotice error={resource.error} reload={resource.reload} loadingText="Đang tải thông báo…" /> : <>{!page.items.length && <p className="notice">Không có thông báo phù hợp.</p>}<ul className="catalog-list">{page.items.map(n => <li key={n.id} className="catalog-panel"><h2>{n.title}</h2><p>{n.body}</p><p>{formatVietnamTime(n.createdAt)} · {n.readAt ? 'Đã đọc' : 'Chưa đọc'}</p>{n.orderId && <Link className="button button-outline" to={(admin ? '/admin/orders/' : '/account/orders/') + n.orderId}>Xem đơn hàng</Link>}{!n.readAt && <SubmitButton type="button" busy={action.busy} onClick={() => void action.run(signal => orderManagement.read(n.id, signal, admin), () => { resource.reload(); window.dispatchEvent(new Event('notifications-changed')) }, 'Đã đánh dấu đã đọc.')}>Đánh dấu đã đọc</SubmitButton>}</li>)}</ul><nav className="catalog-pagination" aria-label="Phân trang thông báo">{[-1, 1].map(step => <SubmitButton key={step} type="button" disabled={step < 0 ? page.page <= 1 : page.page * page.pageSize >= page.totalCount} onClick={() => { const next = new URLSearchParams(params); next.set('page', String(page.page + step)); setParams(next) }}>{step < 0 ? 'Trang trước' : 'Trang sau'}</SubmitButton>)}<span>Trang {page.page} · {page.totalCount} thông báo</span></nav></>}
  </section>
}
